create table public.users (
	user_id INT,
	email VARCHAR(50),
	first_name VARCHAR(50),
	is_accepting_rides VARCHAR(50),
	is_active VARCHAR(50),
	is_driver VARCHAR(50),
	last_name VARCHAR(50),
	phone_number VARCHAR(50),
	user_name TEXT,
	batch_number INT,
	h_address VARCHAR(50),
	w_address VARCHAR(50)
);
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (1, 'ccarlin0@businessweek.com', 'Carma', true, true, true, 'Carlin', '195-561-9291', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 7, '7 Springview Lane', '59 Vera Drive');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (2, 'cbrazenor1@yahoo.co.jp', 'Caldwell', true, false, false, 'Brazenor', '301-272-3200', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 19, '6 Troy Plaza', '97 Delladonna Crossing');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (3, 'cglavis2@abc.net.au', 'Cosette', false, true, false, 'Glavis', '109-578-0202', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 7, '50771 Homewood Plaza', '6 Johnson Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (4, 'bdenisevich3@forbes.com', 'Berrie', false, false, true, 'Denisevich', '833-182-5364', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '83 Stuart Court', '57499 1st Lane');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (5, 'aconigsby4@squidoo.com', 'Ariela', false, true, false, 'Conigsby', '883-888-4268', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '51980 Mallard Way', '687 Little Fleur Court');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (6, 'llogie5@soup.io', 'Luciano', true, false, false, 'Logie', '568-323-2543', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '574 Sunbrook Hill', '224 Valley Edge Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (7, 'vdevons6@photobucket.com', 'Vincents', false, false, false, 'Devons', '335-351-4416', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 4, '1 Mosinee Parkway', '8540 Grasskamp Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (8, 'istenning7@mayoclinic.com', 'Inga', true, true, false, 'Stenning', '289-610-3109', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '868 Birchwood Terrace', '1 Brickson Park Crossing');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (9, 'dpalmby8@altervista.org', 'Dollie', false, true, false, 'Palmby', '497-346-6553', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '97 Melby Hill', '385 2nd Junction');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (10, 'cperegrine9@addtoany.com', 'Curry', false, false, true, 'Peregrine', '312-450-1757', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '66 Artisan Avenue', '92008 Milwaukee Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (11, 'hlawlora@msu.edu', 'Hollie', true, false, true, 'Lawlor', '782-729-6962', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 13, '84 Debra Junction', '444 La Follette Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (12, 'jtuteb@themeforest.net', 'Jehu', false, false, false, 'Tute', '547-934-6281', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '5288 Park Meadow Road', '8 Helena Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (13, 'jhurcombec@linkedin.com', 'Judas', true, true, false, 'Hurcombe', '744-151-9548', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '9 Fuller Street', '6448 Grim Trail');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (14, 'cbuxtond@wp.com', 'Carver', false, false, true, 'Buxton', '406-573-9221', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 3, '47 Declaration Terrace', '231 Carpenter Alley');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (15, 'ikrzysztofiake@tiny.cc', 'Ivan', true, false, true, 'Krzysztofiak', '702-860-8303', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 7, '63 4th Trail', '25 Delaware Parkway');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (16, 'obelliardf@digg.com', 'Ortensia', false, true, false, 'Belliard', '589-508-7259', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '040 John Wall Hill', '04 Dorton Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (17, 'phalleyboneg@t.co', 'Phillis', true, false, false, 'Halleybone', '109-616-8065', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 6, '539 Mcbride Lane', '5272 Rusk Road');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (18, 'gpittfordh@archive.org', 'Gwendolen', true, true, false, 'Pittford', '537-788-0447', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 15, '69 Mayfield Avenue', '60 Di Loreto Junction');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (19, 'cbeddoei@who.int', 'Corbie', true, true, true, 'Beddoe', '862-231-4572', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '0766 Tennyson Crossing', '4038 Canary Drive');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (20, 'agumaryj@canalblog.com', 'Anni', true, true, false, 'Gumary', '804-593-7930', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 13, '62951 Rusk Plaza', '527 Fordem Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (21, 'ofargek@wufoo.com', 'Olly', true, false, false, 'Farge', '585-814-9190', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 13, '172 Dennis Crossing', '38 Arrowood Crossing');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (22, 'klorencel@ovh.net', 'Kylynn', true, true, false, 'Lorence', '894-720-9661', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '67 Superior Junction', '88881 Village Place');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (23, 'cbrunigesm@bloomberg.com', 'Charlton', false, true, true, 'Bruniges', '327-551-7470', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '842 Eggendart Lane', '08 Eagan Park');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (24, 'agrinhamn@adobe.com', 'Allsun', false, true, false, 'Grinham', '862-417-3978', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '461 Corry Crossing', '7876 Caliangt Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (25, 'jhusho@techcrunch.com', 'Joceline', true, true, true, 'Hush', '907-164-1908', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 10, '58 Clemons Parkway', '928 Hazelcrest Terrace');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (26, 'ebortolottip@fema.gov', 'Elsi', false, false, false, 'Bortolotti', '311-734-5149', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '843 Portage Court', '750 Dexter Terrace');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (27, 'gyssonq@chicagotribune.com', 'Gary', true, false, false, 'Ysson', '242-354-6472', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 18, '66 Mendota Way', '2 Arizona Terrace');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (28, 'gliler@theguardian.com', 'Gavra', false, true, false, 'Lile', '251-592-9552', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '8 Homewood Court', '7 Independence Plaza');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (29, 'rpols@cnbc.com', 'Rhody', true, true, false, 'Pol', '358-593-3493', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 15, '6186 7th Pass', '1 8th Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (30, 'tbertelmott@blogger.com', 'Tessie', false, false, true, 'Bertelmot', '142-370-9546', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '77408 Russell Court', '95965 Iowa Lane');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (31, 'mmargramu@digg.com', 'Myca', false, true, false, 'Margram', '320-389-9414', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '723 Heffernan Lane', '3083 Northridge Road');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (32, 'fduckerv@cornell.edu', 'Flore', false, false, true, 'Ducker', '975-761-3761', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 3, '2670 Sage Trail', '220 Goodland Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (33, 'sratcliffw@topsy.com', 'Sig', false, false, true, 'Ratcliff', '995-141-5853', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 19, '8699 Westerfield Circle', '96137 Harper Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (34, 'chutchasonx@phoca.cz', 'Ciro', false, true, false, 'Hutchason', '328-271-1754', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '648 4th Hill', '35888 Anhalt Lane');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (35, 'kgookeyy@liveinternet.ru', 'Kimberli', true, true, true, 'Gookey', '554-255-4604', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 20, '843 Butternut Alley', '1494 Summit Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (36, 'dstainesz@tumblr.com', 'Dode', false, true, false, 'Staines', '736-107-4994', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 13, '5480 Maryland Plaza', '537 Merry Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (37, 'flindermann10@privacy.gov.au', 'Fowler', true, true, true, 'Lindermann', '404-135-2311', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '1 Spenser Junction', '60 Commercial Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (38, 'mclifft11@webnode.com', 'Marsha', false, false, true, 'Clifft', '262-895-2932', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '54986 Wayridge Alley', '5 Truax Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (39, 'lbritton12@xinhuanet.com', 'Leshia', false, false, true, 'Britton', '244-551-9153', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 3, '33210 Northland Alley', '7766 Mccormick Park');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (40, 'mvedishchev13@intel.com', 'Mohammed', false, true, false, 'Vedishchev', '378-311-9294', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 19, '2197 Butternut Junction', '189 Reindahl Court');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (41, 'vhow14@loc.gov', 'Vivian', true, false, false, 'How', '384-624-8149', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '8 Sommers Hill', '18 Kipling Alley');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (42, 'apontain15@psu.edu', 'Adda', true, true, true, 'Pontain', '574-992-8061', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '8 Scofield Terrace', '273 Ilene Plaza');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (43, 'ccrocumbe16@goo.gl', 'Cross', false, true, false, 'Crocumbe', '675-675-3449', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '1 Sloan Junction', '68838 New Castle Plaza');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (44, 'jwhellans17@cmu.edu', 'Jeanette', true, true, true, 'Whellans', '941-261-6663', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '6383 Dakota Hill', '392 Loomis Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (45, 'fmasey18@guardian.co.uk', 'Farra', false, true, true, 'Masey', '140-260-6534', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '5 Steensland Avenue', '72 Dawn Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (46, 'sreinger19@woothemes.com', 'Sayer', false, false, false, 'Reinger', '274-731-6719', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 11, '029 Mayfield Park', '973 Acker Junction');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (47, 'gjoberne1a@umich.edu', 'Gloriana', false, false, false, 'Joberne', '257-302-4474', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 1, '6918 Anniversary Center', '774 Arrowood Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (48, 'obaumann1b@gravatar.com', 'Ola', false, false, false, 'Baumann', '888-898-7992', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 5, '82 South Park', '02 Columbus Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (49, 'mdalla1c@technorati.com', 'Mariejeanne', true, false, false, 'Dalla', '962-374-2723', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 20, '8916 Stoughton Circle', '7744 Orin Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (50, 'mhullock1d@cargocollective.com', 'Maddy', true, true, true, 'Hullock', '692-647-2041', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 13, '45 Larry Point', '1 Waxwing Place');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (51, 'rhannam1e@wikipedia.org', 'Roselia', true, true, true, 'Hannam', '117-926-4594', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '15710 Forest Lane', '9149 Nevada Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (52, 'tstarkings1f@umich.edu', 'Tyson', true, true, true, 'Starkings', '960-115-8302', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '6 Sage Park', '36747 Sutteridge Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (53, 'ablindmann1g@omniture.com', 'Andrey', true, true, false, 'Blindmann', '218-987-7332', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 6, '97 Bluejay Point', '21 Manitowish Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (54, 'apetracchi1h@google.ru', 'Adele', true, false, false, 'Petracchi', '371-262-5826', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '9 Bobwhite Terrace', '53717 Buhler Court');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (55, 'pmatashkin1i@cnbc.com', 'Perren', false, true, false, 'Matashkin', '413-934-1876', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 5, '315 Fordem Hill', '61 Schmedeman Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (56, 'mstearn1j@angelfire.com', 'Maren', true, false, true, 'Stearn', '163-980-5949', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 4, '70596 Briar Crest Point', '3 Longview Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (57, 'ngrason1k@istockphoto.com', 'Nessie', false, false, true, 'Grason', '889-408-1362', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 12, '5 Sundown Terrace', '4232 Eastlawn Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (58, 'gmarlin1l@cbc.ca', 'Gayle', true, false, true, 'Marlin', '918-701-2640', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '9066 Bartillon Crossing', '6627 Anniversary Crossing');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (59, 'hstukings1m@independent.co.uk', 'Harv', false, true, true, 'Stukings', '619-719-3976', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 11, '106 Arrowood Park', '7574 Northridge Trail');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (60, 'cbattram1n@phoca.cz', 'Cale', false, false, false, 'Battram', '114-324-1888', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '02 Crescent Oaks Street', '640 Cody Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (61, 'bdumberrill1o@intel.com', 'Berthe', true, false, false, 'Dumberrill', '257-522-0789', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '02243 Clarendon Crossing', '8 Donald Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (62, 'tmapam1p@guardian.co.uk', 'Trudey', true, false, false, 'Mapam', '895-695-2015', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '09 Tony Center', '0 Vernon Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (63, 'agetten1q@telegraph.co.uk', 'Arv', false, false, false, 'Getten', '631-283-7392', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '7 Evergreen Park', '511 Bluestem Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (64, 'obeedell1r@reverbnation.com', 'Omar', true, false, false, 'Beedell', '908-696-5000', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 11, '5480 Roxbury Point', '0877 Mallard Trail');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (65, 'chastin1s@jiathis.com', 'Clim', true, true, true, 'Hastin', '532-231-1733', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '04561 6th Hill', '58 Annamark Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (66, 'jpayle1t@cbc.ca', 'Jere', true, true, true, 'Payle', '686-175-9002', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '2927 Helena Center', '1 Haas Park');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (67, 'tjameson1u@columbia.edu', 'Trix', false, false, true, 'Jameson', '977-765-6039', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '082 Duke Place', '21339 4th Lane');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (68, 'escoullar1v@china.com.cn', 'Emelita', false, false, false, 'Scoullar', '537-730-4489', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 18, '2 1st Pass', '3182 Quincy Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (69, 'hbosward1w@rakuten.co.jp', 'Hettie', true, false, true, 'Bosward', '528-289-2622', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 4, '75 Dunning Road', '57 Crest Line Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (70, 'fdurham1x@hatena.ne.jp', 'Felita', false, true, false, 'Durham', '635-981-7833', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '72 Butternut Circle', '218 Little Fleur Terrace');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (71, 'mblackly1y@a8.net', 'Mal', false, false, false, 'Blackly', '736-808-1314', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 6, '92649 Fulton Court', '92 Oxford Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (72, 'gwickins1z@nbcnews.com', 'Gamaliel', false, true, false, 'Wickins', '331-669-6574', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 11, '9 Main Lane', '2 Melvin Park');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (73, 'acutforth20@twitpic.com', 'Anastasie', false, false, true, 'Cutforth', '311-964-7439', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 19, '54 Blackbird Lane', '5299 Morning Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (74, 'pmartill21@icq.com', 'Pauli', false, false, false, 'Martill', '540-138-5800', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 16, '194 Sutteridge Pass', '851 Warner Trail');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (75, 'cnowill22@usgs.gov', 'Corbet', false, false, true, 'Nowill', '773-953-9891', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 7, '902 Huxley Avenue', '13 Center Way');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (76, 'bbeaconsall23@weibo.com', 'Brander', true, true, false, 'Beaconsall', '525-938-9254', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 18, '3618 Bultman Lane', '30315 Fuller Hill');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (77, 'tcorrison24@photobucket.com', 'Tammie', true, true, true, 'Corrison', '609-324-8291', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 4, '919 Jenna Pass', '7 Mallard Avenue');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (78, 'bworssam25@who.int', 'Bryna', false, false, true, 'Worssam', '385-256-8850', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 7, '9 Springview Point', '51450 Lindbergh Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (79, 'egurden26@sina.com.cn', 'Erin', true, true, true, 'Gurden', '463-614-6897', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 18, '36843 Sloan Drive', '1 Pawling Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (80, 'asoal27@cnet.com', 'Aleksandr', false, true, false, 'Soal', '205-179-0051', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '092 Merchant Parkway', '52 Hoard Crossing');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (81, 'dsindell28@goo.gl', 'Durante', false, false, false, 'Sindell', '561-530-6928', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 1, '6585 Holy Cross Park', '745 Rockefeller Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (82, 'awidmore29@ucoz.com', 'Ardenia', true, true, false, 'Widmore', '564-639-5110', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 8, '558 Eastlawn Avenue', '948 Bobwhite Alley');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (83, 'ldotterill2a@dion.ne.jp', 'Leona', false, true, true, 'Dotterill', '957-847-3242', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 20, '1183 3rd Terrace', '812 Lindbergh Park');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (84, 'jpigeon2b@unblog.fr', 'Janek', true, false, false, 'Pigeon', '978-966-4336', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 17, '7 Red Cloud Place', '048 Logan Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (85, 'bcanario2c@unblog.fr', 'Barnie', false, true, true, 'Canario', '449-667-0660', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 2, '96 Becker Street', '12249 Dawn Hill');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (86, 'qknightsbridge2d@discuz.net', 'Quinn', true, true, false, 'Knightsbridge', '920-223-5617', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 14, '4712 Duke Point', '699 Bay Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (87, 'crakestraw2e@barnesandnoble.com', 'Carrie', true, true, false, 'Rakestraw', '815-777-8004', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 20, '1484 Old Gate Place', '5956 Summerview Street');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (88, 'tjansson2f@altervista.org', 'Trix', true, false, true, 'Jansson', '938-848-7938', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 1, '00499 Red Cloud Plaza', '9 2nd Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (89, 'awoolf2g@geocities.com', 'Anne-corinne', false, true, false, 'Woolf', '847-991-5096', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 10, '487 Moose Parkway', '093 Springs Place');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (90, 'ggleave2h@exblog.jp', 'Gabby', true, false, true, 'Gleave', '360-728-5116', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 11, '48680 Jenifer Street', '05 Veith Circle');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (91, 'iewbanck2i@arizona.edu', 'Ivette', false, false, true, 'Ewbanck', '316-918-3722', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 3, '71251 Continental Park', '6 2nd Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (92, 'sstack2j@rambler.ru', 'Sawyere', true, false, true, 'Stack', '424-161-1297', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 4, '68 Westridge Trail', '5031 Crescent Oaks Parkway');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (93, 'rdeveraux2k@bigcartel.com', 'Ransom', true, true, false, 'Deveraux', '331-668-6402', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 1, '822 Randy Parkway', '124 Fuller Point');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (94, 'celcocks2l@vinaora.com', 'Conant', false, false, false, 'Elcocks', '320-668-6824', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '5210 Monica Court', '13859 Fallview Plaza');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (95, 'rwhittlesey2m@salon.com', 'Rodie', false, true, true, 'Whittlesey', '157-469-9574', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 10, '2063 Arapahoe Road', '484 Donald Drive');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (96, 'nfarmer2n@i2i.jp', 'Nancee', true, true, true, 'Farmer', '844-601-6000', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '7288 Waubesa Terrace', '6451 Clove Alley');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (97, 'mkitchingman2o@xrea.com', 'Misty', false, false, false, 'Kitchingman', '131-796-4158', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '6544 Mccormick Hill', '0558 Union Center');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (98, 'kheather2p@cpanel.net', 'Kirbee', false, true, false, 'Heather', '832-871-7846', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 19, '22138 Hallows Trail', '38069 Granby Pass');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (99, 'gpiens2q@icio.us', 'Glynis', false, true, false, 'Piens', '799-153-1255', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 9, '6900 Birchwood Drive', '392 Namekagon Trail');
insert into public.users (user_id, email, first_name, is_accepting_rides, is_active, is_driver, last_name, phone_number, user_name, batch_number, h_address, w_address) values (100, 'mmowatt2r@joomla.org', 'Marlane', true, false, false, 'Mowatt', '787-818-3855', 'error: Please use field(''UNIQUE'') to access UNIQUE because it starts with an upper case letter.', 20, '9 Shopko Place', '03182 Schlimgen Place');
